# Deep Learning with PyTorch


Author: [Anand Saha](http://teleported.in/)

### 1.5 Tensors and Tensor operations

**Objective**: Get hands on with Tensor creation and operations

`torch` package contains the necessary data structures to create multi dimentional Tensors. It also defines the mathematical operations that can be performed on these.

In [2]:
import torch

In [3]:
print(torch.__version__)

2.3.1+cpu


### Tensor creation

Create a (2x3) dimentional Tensor.

Note that a) You get back a FloatTensor b) The values are uninitialized

In [4]:
t = torch.Tensor(2, 3)
print(t)

tensor([[-5.6874e-14,  8.5479e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


The above call was equivalent to

In [5]:
t = torch.FloatTensor(2, 3)
print(t)

tensor([[-5.6875e-14,  8.5479e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Inspect type of an element

In [6]:
t[0][0]

tensor(-5.6875e-14)

In [7]:
type(t[0][0])

torch.Tensor

Inspect `t`'s dimensions

In [8]:
print(t.size())
print(t.dim())
print(len(t.size()) == t.dim())

torch.Size([2, 3])
2
True


Set values

In [9]:
t[0][0] = 1
t[0][1] = 2
t[0][2] = 3
t[1][0] = 4
t[1][1] = 5
t[1][2] = 6
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


Let's cast a FloatTensor to IntTensor

In [10]:
t = torch.FloatTensor([1.1, 2.2])
print(t)
t.type(torch.IntTensor)

tensor([1.1000, 2.2000])


tensor([1, 2], dtype=torch.int32)

Let's explore some other ways of creating a tensor

In [11]:
# From another Tensor

t2 = torch.Tensor(t)
print(t2)

tensor([1.1000, 2.2000])


In [12]:
# From a Python list

t3 = torch.IntTensor([[1, 2],[3, 4]])
print(t3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [13]:
# From a NumPy array

import numpy as np
a = np.array([55, 66])
t4 = torch.Tensor(a)
print(t4)

tensor([55., 66.])


In [14]:
# Create a Tensor with all zeros

t5 = torch.zeros(2, 3)
print(t5)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# Create a Tensor with all ones

t6 = torch.ones(2, 3)
print(t6)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
# Create a Tensor with all ones with dimensions 
# of another Tensor

t7 = torch.ones_like(t4)
print(t7)

tensor([1., 1.])


### Tensor operations

Add two Tensors

In [17]:
t1 = torch.ones(2, 2)
t2 = torch.ones(2, 2)
t = t1 + t2
print(t)

tensor([[2., 2.],
        [2., 2.]])


Inplace/out-of-place operations

In [18]:
t1.add(t2)

tensor([[2., 2.],
        [2., 2.]])

In [19]:
print(t1)

tensor([[1., 1.],
        [1., 1.]])


In [20]:
t1.add_(t2)

tensor([[2., 2.],
        [2., 2.]])

In [21]:
print(t1)

tensor([[2., 2.],
        [2., 2.]])


Class methods and package functions

In [22]:
t1.cos()

tensor([[-0.4161, -0.4161],
        [-0.4161, -0.4161]])

In [23]:
torch.cos(t1)

tensor([[-0.4161, -0.4161],
        [-0.4161, -0.4161]])

A few more operations

In [24]:
# Create a one-dimensional tensor of steps equally 
# spaced points between start and end

torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [25]:
# Create a 1-D Tensor with values from [start, end)

torch.arange(0, 5)

tensor([0, 1, 2, 3, 4])

In [26]:
# Create a (2x3) Tensor with random values sampled 
# from uniform distrubution on the interval [0,1)

torch.rand((2,3))

tensor([[0.9298, 0.0755, 0.6452],
        [0.7175, 0.9919, 0.9964]])

In [ ]:
# Create a (2x3) Tensor with random values sampled 
# from normal distrubution with 0 mean and variance 1

torch.randn((2,3))

In [ ]:
# Do a matrix multiply

a = torch.rand((2, 3))
b = torch.rand((3, 2))

torch.mm(a, b)

`Explore more operations at:` http://pytorch.org/docs/0.3.0/tensors.html