# Deep Learning with PyTorch


Author: [Anand Saha](http://teleported.in/)

### 1.5 Variables

**Objective**: Understand Variables and operations on them

In [1]:
import torch
from torch.autograd import Variable

Let's create a small computation graph

In [2]:
x = Variable(torch.FloatTensor([11.2]), requires_grad=True)
y = 2 * x

In [3]:
print(x)
print(y)

tensor([11.2000], requires_grad=True)
tensor([22.4000], grad_fn=<MulBackward0>)


In [4]:
print(x.data)
print(y.data)

tensor([11.2000])
tensor([22.4000])


In [5]:
print(x.grad_fn)
print(y.grad_fn)

None


In [6]:
y.backward() # Calculates the gradients

In [7]:
print(x.grad)
print(y.grad)

tensor([2.])
None


C:\Users\spran\AppData\Local\Temp\ipykernel_16208\106071707.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  print(y.grad)
